### ISSUE TITLE
VMCS - Defect in resetting the values to null upon re-login to the maintenance panel in the same session

### ISSUE THREAD

**Issue by neelimabenny21** [AbhijitGite28/vmcs#1]
The simulation currently does not clear the values on the completion of a Maintenance session. Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and already collected, persists in the display screen causing confusion to the Maintainer.

Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the
Maintainer successfully pushes “Press Here When Finished”.

**Comment by keerpari** [comment]
By analyzing, I found that DMR document need to changes to the following sections.

Sequence diagram:
1. 3.6.6:Sequence diagram for Display Total Cash
2. 3.6.7:Sequence diagram for Logout (1)
3. 3.9.2:Sequence diagram for Maintenance Panel

Functions:
1. 4.6.11 Maintenance Controller

**Comment by keerpari** [comment]
As a Technical Lead i have reviewed and updated the Design Model Report .

**Comment by blackpanther2712** [comment]
Issue has been **fixed**.

**Comment by neelimabenny21** [comment]
As a Quality Analyst/ Tester, I have reviewed the design model report changes and conducted integration testing. Integration tests have been successfully passed.

**Comment by neelimabenny21** [comment]
From Project Manager,
The defect-fix is now under UAT.

**Comment by gowthamkg11** [comment]
UAT has passed successfully.

**Comment by neelimabenny21** [comment]
From Project Manager, UAT has successfully completed.
