### ISSUE TITLE
VMCS - Enhancement to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer.

### ISSUE THREAD

**Issue by neelimabenny21** [AbhijitGite28/vmcs#2]
An enhancement is identified to provide an at-a-glance display of the cash amount available, by
denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally
the total cash collected and the total number of coins by denomination displayed in “Show
Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute
over system errors.

Upon successfully logging in to the drinks dispenser machine,

a. The Maintainer must be able to press “Show Total Cash Held’ upon which, a
display of not only the Total Cash Held should be displayed, the specific Quantity of
coins per denomination together with its total cash Amount/value per
denomination should be calculated and displayed.

b. The Maintainer must be able to more readily compare the individual Amount
by denomination with the Total Cash Held.

c. Once the Maintainer pushes the “Press To Collect All Cash”, the number
of coins dispensed must tally with the total number of coins in inventory for
each denomination.

d. Finally, the Maintainer will simulate to indicate “Door Locked” in the
Machinery Panel, as per normal, and will “Press Here When Finished” his
routine maintenance on the vending machine.

**Comment by blackpanther2712** [comment]
After analyzing the enhancement requested, I found that these are the **sections** that would require improvisation in the Design Model:

**Sequence Diagram Flows:** 
3.6.9 Sequence Diagram: Sequence Diagram: Update Coin Display
3.7.1	 Sequence Diagram: Sequence Diagram: Transfer All Cash

**Functions:** 
4.6.6 Coin Display
4.4.12 Store Controller
4.6.11 Maintenance Controller	
4.6.12 Maintenance Panel
4.6.18 CoinLabelItem	
4.6.19 CoinLabelItemDisplay

**Comment by keerpari** [comment]
As a Technical Lead i have reviewed and updated the Design Model Report .

**Comment by gowthamkg11** [comment]
Issue has been fixed

**Comment by neelimabenny21** [comment]
As a Quality Analyst/ Tester, I have reviewed the design model report changes and conducted integration testing. Integration tests have been successfully passed.

**Comment by neelimabenny21** [comment]
From Project Manager,
The enhancement is now under UAT.

**Comment by gowthamkg11** [comment]
UAT has passed successfully.

**Comment by neelimabenny21** [comment]
From Project Manager, UAT has successfully completed.
